---
project: deblur_gan
experiment_desc: fpn

train:
  files_a: &FILES_A /home/arseny/datasets/SIDD_Medium_Srgb/Data/*/*NOISY*.PNG
  files_b: &FILES_B /home/arseny/datasets/SIDD_Medium_Srgb/Data/*/*GT*.PNG
  size: &SIZE 256
  scope: strong
  crop: random
  preload: &PRELOAD true
  preload_size: &PRELOAD_SIZE 0
  bounds: [0, .9]
val:
  files_a: *FILES_A
  files_b: *FILES_B
  size: *SIZE
  scope: weak
  crop: center
  preload: *PRELOAD
  preload_size: *PRELOAD_SIZE
  bounds: [.9, 1]

phase: train
warmup_num: 3
model:
  g_name: fpn_inception
  blocks: 9
  d_name: patch_gan
  d_layers: 3
  content_loss: perceptual
  adv_lambda: 0.001
  disc_loss: wgan-gp
  learn_residual: True
  norm_layer: instance
  dropout: True
num_epochs: 100
batch_size: 8
image_size: [256, 256]
fineSize: 256
dataset:
  task: dehaze
optimizer:
  name: adam
  lr: 0.0001
scheduler:
  name: linear
  start_epoch: 50
  min_lr: 0.0000001

