---
project: deblur_gan
experiment_desc: default_experiment
dataroot_train: /home...
dataroot_val: /home... 
warmup_num: 0
model:
    g_name: resnet
    blocks: 9
    d_name: n_layers
    d_layers: 3
    content_loss: perceptual
    disc_loss: wgan-gp
    learn_residual: True
    backbone: resnet34
    pretrained: False
    norm_layer: instance
    dropout: True  
num_epochs: 100
num_workers: 8
batch_size: 64
image_size: [256, 256]
dataset: 
    mode: unaligned
optimizer: 
    name: adam
    lr: 0.0001
scheduler:
    name: plateau
    patience: 5
    factor: 0.5
    min_lr: 0.0000001

